/*	Euler problem 2
*	URL: http://projecteuler.net/problem=2
*
*	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
*
*	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
*	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
function euler_2() {
	var num1 = 1;
	var num2 = 2;
	var nextNum;
	var sum = 0;
	
	//	Intializes sum if num1 is an even number
	if (num1 % 2 == 0)
		sum = num1;

	//	Loops until the value of the next term of the fibonacci sequence is greater then 4 million
	do {
		//	Checks if value is even
		if (num2 % 2 == 0)
			sum += num2;
		
		//	Finds next term in the sequence
		nextNum = num1 + num2;
		
		//	Shifts the sequence to the left
		num1 = num2;
		num2 = nextNum;
	} while (nextNum < 4000000);		
	
	return sum;
}