# Project Euler ~ Problem 2
# http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms.By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


num1 = 1
num2 = 2
tempNum = 0
sumNum = 0
highestTerm = 4000000

while num1 <= highestTerm and num2 <= highestTerm :
    if num2 % 2 == 0:
        sumNum += num2
    tempNum = num1 + num2
    num1 = num2
    num2 = tempNum

print sumNum
